In [1]:
import pyarrow

In [2]:
import os
import random
import string
import pandas as pd
from datetime import datetime
import time
import json
import numpy as np

def generate_random_variable(value_type: str) -> str:
    """
    Generate a random variable by string type.

    Args:
        value_type: Variable type.

    Returns:
        Respective type variable.
    """

    if value_type == 'int':
        return str(random.randrange(20))
    elif value_type == 'str':
        letters = string.ascii_lowercase
        return ''.join(random.choice(letters) for _ in range(10))
    elif value_type == 'phone':
        number = [str(random.randrange(9)) for _ in range(9)]
        return ''.join(number)
    elif value_type == 'long_int':
        number = [str(random.randrange(9)) for _ in range(11)]
        return ''.join(number)
    elif value_type == 'float':
        return str(random.random()).replace(".", ",")
    elif value_type == 'operation':
        return random.choice(['INSERT', 'UPDATE', 'DELETE'])
    elif value_type == 'timestamp':
#         return str(time.time())
        return "1563551566.9326966"
    elif value_type == 'date':
        return datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d-%H-%M-%S')
    else:
        return ''


def generate_random_row(cols: dict) -> dict:
    """
    Generate a dataframe row with random values. The number of columns and its type are defined by ``cols`` parameter.

    Args:
        cols: Dictionary with the dataframe respective cols and its type.

    Returns:
        Dictionary row of the dataframe.
    """

    row = {}
    for key, value in cols.items():
        row[key] = generate_random_variable(value)

    return row

In [3]:
df = []
num_rows = 20
cols = {
            'unique_id': 'int',
            'name': 'str',
            'phone': 'phone',
            'cpf': 'long_int',
            'age': 'int',
            'budget': 'float',
            'timestamp': 'timestamp',
            'line': 'str',
            'retry': 'int',
            'update_date': 'date',
            'source_files': 'str'
        }

for _ in range(num_rows):
    df.append(generate_random_row(cols))

df = pd.DataFrame(df)
df['unique_id'] = np.random.permutation(num_rows)

In [4]:
df

,age,budget,cpf,line,name,phone,retry,source_files,timestamp,unique_id,update_date
0,18,"0,9387888614917022",72011821002,taxcvuhodh,hxpevhgkxj,631352582,2,txezeplqbo,1563551566.9326966,15,2019-07-25-11-18-40
1,6,"0,8323758282817877",37370402438,gazzmrfhzk,qblvdpkggj,523453733,10,xvxtxcnmti,1563551566.9326966,9,2019-07-25-11-18-40
2,13,"0,0938481444935233",28718713071,ysqxqhlvgb,mlwhecflmx,682178076,19,apebuoykdb,1563551566.9326966,5,2019-07-25-11-18-40
3,0,"0,4303791150095593",50576615770,rxrpewfrug,nrlwltwifa,546848313,9,wgkgsgtwmf,1563551566.9326966,14,2019-07-25-11-18-40
4,7,"0,746746715834829",86015107566,vtgacbwipm,crzwjhubpb,655836270,0,rivdxrwjea,1563551566.9326966,8,2019-07-25-11-18-40
5,6,"0,9546045939852003",42670614412,sfubxxwcnx,ugcomjmgnp,827373533,9,bkbkhibjew,1563551566.9326966,13,2019-07-25-11-18-40
6,10,"0,9419315657665351",78123473570,kgiqbfntdx,gukzvwnoos,645458382,13,rkyziuszja,1563551566.9326966,1,2019-07-25-11-18-40
7,15,"0,2882736557565153",74131668513,bmomgcjkej,chuamcsbdr,015875830,8,nexfjkjlaz,1563551566.9326966,6,2019-07-25-11-18-40
8,19,"0,11065196887310647",31366554813,lycygdmola,esqreodoup,466757023,2,ruzkdnaoak,1563551566.9326966,2,2019-07-25-11-18-40
9,10,"0,809113266119962",53006851844,mizegyrzhb,mmhuthsiew,880455667,13,dztufegcef,1563551566.9326966,4,2019-07-25-11-18-40
10,10,"0,8867641680722449",60402821432,dojswciiiv,qaakppvate,357027300,13,bnacftkndh,1563551566.9326966,16,2019-07-25-11-18-40
11,2,"0,8870571086617877",17200648260,ocdkhzmnoo,ogtrxrvjbt,013108076,15,nrxeufzbmg,1563551566.9326966,10,2019-07-25-11-18-40
12,15,"0,004602751200462052",21484023816,cenbmjkagb,hklcgpznms,470063811,6,hqkbkcadnj,1563551566.9326966,12,2019-07-25-11-18-40
13,7,"0,7134081889196423",51328542532,brcjwxdtpj,aambgwezvb,027742244,18,watctoeaky,1563551566.9326966,19,2019-07-25-11-18-40
14,13,"0,605288466388206",15383031776,oqyrlzbewg,vvcelmuclg,426856684,17,jtkhtparjh,1563551566.9326966,18,2019-07-25-11-18-40
15,0,"0,45357371065256546",08641834000,jydozdfnfs,rgzvxospqi,437356655,4,pjhqrdtgpy,1563551566.9326966,3,2019-07-25-11-18-40
16,18,"0,9099616005679396",70544142165,fldacodapo,lrpvfbqicy,433860008,12,mtxlccrybe,1563551566.9326966,7,2019-07-25-11-18-40
17,11,"0,8092487924797553",21746015376,vlgttztorx,fsdormuhxm,003451724,15,brjhxcxvxu,1563551566.9326966,11,2019-07-25-11-18-40
18,0,"0,9621503293543384",78328676707,umsgdnvxsk,mptekfexqt,402457330,12,wduvwromux,1563551566.9326966,0,2019-07-25-11-18-40
19,0,"0,3418548634542593",55404157125,sqtknxdnwr,pkzctrjzah,225608757,7,rdzhkcuvez,1563551566.9326966,17,2019-07-25-11-18-40

In [5]:
df.to_parquet('../GIT/rdr010/data_lake/tests/resources/test_data.parquet', index=False)

In [6]:
import pyarrow as pa
t = pa.parquet.read_table('../GIT/rdr010/data_lake/tests/resources/test_data.parquet')

In [7]:
bt = bytearray('../GIT/rdr010/data_lake/tests/resources/test_data.parquet', 'utf-8')

In [8]:
with open('../GIT/rdr010/data_lake/tests/resources/test_data.parquet', mode='rb') as file:
    t = file.read()

In [11]:
import io
df2 = pd.read_parquet(io.BytesIO(t))

In [12]:
df2["unique_id"]

0     15
1      9
2      5
3     14
4      8
5     13
6      1
7      6
8      2
9      4
10    16
11    10
12    12
13    19
14    18
15     3
16     7
17    11
18     0
19    17
Name: unique_id, dtype: int64