In [1]:
import pyarrow

ModuleNotFoundError: No module named 'pyarrow'

In [19]:
import os
import random
import string
import pandas as pd
from datetime import datetime
import time
import json
import numpy as np

def generate_random_variable(value_type: str) -> str:
    """
    Generate a random variable by string type.

    Args:
        value_type: Variable type.

    Returns:
        Respective type variable.
    """

    if value_type == 'int':
        return str(random.randrange(20))
    elif value_type == 'str':
        letters = string.ascii_lowercase
        return ''.join(random.choice(letters) for _ in range(10))
    elif value_type == 'phone':
        number = [str(random.randrange(9)) for _ in range(9)]
        return ''.join(number)
    elif value_type == 'long_int':
        number = [str(random.randrange(9)) for _ in range(11)]
        return ''.join(number)
    elif value_type == 'float':
        return str(random.random()).replace(".", ",")
    elif value_type == 'operation':
        return random.choice(['INSERT', 'UPDATE', 'DELETE'])
    elif value_type == 'timestamp':
#         return str(time.time())
        return "1563551566.9326966"
    elif value_type == 'date':
        return datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d-%H-%M-%S')
    else:
        return ''


def generate_random_row(cols: dict) -> dict:
    """
    Generate a dataframe row with random values. The number of columns and its type are defined by ``cols`` parameter.

    Args:
        cols: Dictionary with the dataframe respective cols and its type.

    Returns:
        Dictionary row of the dataframe.
    """

    row = {}
    for key, value in cols.items():
        row[key] = generate_random_variable(value)

    return row

In [20]:
df = []
num_rows = 20
cols = {
            'unique_id': 'int',
            'name': 'str',
            'phone': 'phone',
            'cpf': 'long_int',
            'age': 'int',
            'budget': 'float',
            'timestamp': 'timestamp',
            'line': 'str',
            'retry': 'int',
            'update_date': 'date',
            'source_files': 'str'
        }

for _ in range(num_rows):
    df.append(generate_random_row(cols))

df = pd.DataFrame(df)
df['unique_id'] = np.random.permutation(num_rows)

In [21]:
df

,age,budget,cpf,line,name,phone,retry,source_files,timestamp,unique_id,update_date
0,14,"0,5230898621228263",51170350338,cziqxywdim,cffayqtiob,081717024,8,iqsidciovl,1563551566.9326966,13,2019-07-22-09-04-54
1,6,"0,4319350843682602",42325323503,cynfnwachs,kgdovphuph,888018324,10,knfwylcqfm,1563551566.9326966,8,2019-07-22-09-04-54
2,17,"0,43996190238047905",25601648606,rhorkzipfj,cmwxotlewi,677675127,17,uhqqqwrfdo,1563551566.9326966,14,2019-07-22-09-04-54
3,14,"0,48279060235822147",56271475063,fsdwcrgmgd,chkgscarlb,288753777,12,xqhludfssc,1563551566.9326966,6,2019-07-22-09-04-54
4,8,"0,9536048530680995",06736675502,juvzevnnxp,ucfvlpznqc,303150375,10,hizyskenxj,1563551566.9326966,19,2019-07-22-09-04-54
5,18,"0,6267432647396652",35140528511,kkonelndmf,qnluioyzxp,567667383,7,amcrkrrxaa,1563551566.9326966,8,2019-07-22-09-04-54
6,5,"0,35447012561420677",72578607535,rgpuxdbzeo,oboqecquqk,386603336,7,oedideecgo,1563551566.9326966,8,2019-07-22-09-04-54
7,11,"0,7062715013304485",74125106645,jblfzvzrfn,prtydkzhtg,284614451,0,wggisepukx,1563551566.9326966,1,2019-07-22-09-04-54
8,10,"0,47674953719536506",71266804082,abpvjjkohy,dwwnolyesw,867004405,9,yusgabwlvb,1563551566.9326966,4,2019-07-22-09-04-54
9,0,"0,7461456226596285",53277654580,ecdroalxjh,psaopyiwsu,861741317,2,ehjfwunwxn,1563551566.9326966,9,2019-07-22-09-04-54
10,3,"0,19512019892227683",66010751775,ylnajafonx,mhwrahnehb,745283041,0,jhnusvhmsh,1563551566.9326966,16,2019-07-22-09-04-54
11,19,"0,8950395090491776",45546662582,urknwzolpt,ddsenmeptw,008428241,4,qldrjqgdiz,1563551566.9326966,6,2019-07-22-09-04-54
12,13,"0,9637519061762126",12563485211,ixzfzcwywr,petghpwvof,358783673,17,wmtdokbzyg,1563551566.9326966,7,2019-07-22-09-04-54
13,6,"0,9034054349673653",58328522035,rjxqxkrzcm,vfotskpudh,646064825,7,adwutkucrp,1563551566.9326966,10,2019-07-22-09-04-54
14,12,"0,6604900829914974",16401581386,wgphkbrgwq,pelwqhoebz,646100585,12,wulnahbfiq,1563551566.9326966,0,2019-07-22-09-04-54
15,4,"0,1341989018272597",43638668847,vmmsbdrfjm,beamrudcth,060444042,19,dkwwbsbjkl,1563551566.9326966,14,2019-07-22-09-04-54
16,1,"0,03862737153098439",71647511272,ycuwucbzgp,bswobivool,021338683,18,voqejluriu,1563551566.9326966,14,2019-07-22-09-04-54
17,8,"0,8519048289064296",27424413773,sgmxozsopz,disuahpxcx,254616675,17,yktnjnfhvh,1563551566.9326966,4,2019-07-22-09-04-54
18,5,"0,29459793082768704",12313186266,mhudrtjkog,lnfuuvbuts,046064645,10,rwqeohlfxk,1563551566.9326966,12,2019-07-22-09-04-54
19,9,"0,15588239527338066",65254172167,tfkmcsauxe,abeqwrtyft,800053706,16,lpezwljgul,1563551566.9326966,10,2019-07-22-09-04-54

In [22]:
df.to_parquet('../GIT/rdr010/data_lake/tests/resources/test_data.parquet', index=False)

In [23]:
import pyarrow as pa
t = pa.parquet.read_table('../GIT/rdr010/data_lake/tests/resources/test_data.parquet')

In [24]:
bt = bytearray('../GIT/rdr010/data_lake/tests/resources/test_data.parquet', 'utf-8')

In [25]:
with open('../GIT/rdr010/data_lake/tests/resources/test_data.parquet', mode='rb') as file:
    t = file.read()

In [26]:
import io
pd.read_parquet(io.BytesIO(t))

,age,budget,cpf,line,name,phone,retry,source_files,timestamp,unique_id,update_date
0,14,"0,5230898621228263",51170350338,cziqxywdim,cffayqtiob,081717024,8,iqsidciovl,1563551566.9326966,13,2019-07-22-09-04-54
1,6,"0,4319350843682602",42325323503,cynfnwachs,kgdovphuph,888018324,10,knfwylcqfm,1563551566.9326966,8,2019-07-22-09-04-54
2,17,"0,43996190238047905",25601648606,rhorkzipfj,cmwxotlewi,677675127,17,uhqqqwrfdo,1563551566.9326966,14,2019-07-22-09-04-54
3,14,"0,48279060235822147",56271475063,fsdwcrgmgd,chkgscarlb,288753777,12,xqhludfssc,1563551566.9326966,6,2019-07-22-09-04-54
4,8,"0,9536048530680995",06736675502,juvzevnnxp,ucfvlpznqc,303150375,10,hizyskenxj,1563551566.9326966,19,2019-07-22-09-04-54
5,18,"0,6267432647396652",35140528511,kkonelndmf,qnluioyzxp,567667383,7,amcrkrrxaa,1563551566.9326966,8,2019-07-22-09-04-54
6,5,"0,35447012561420677",72578607535,rgpuxdbzeo,oboqecquqk,386603336,7,oedideecgo,1563551566.9326966,8,2019-07-22-09-04-54
7,11,"0,7062715013304485",74125106645,jblfzvzrfn,prtydkzhtg,284614451,0,wggisepukx,1563551566.9326966,1,2019-07-22-09-04-54
8,10,"0,47674953719536506",71266804082,abpvjjkohy,dwwnolyesw,867004405,9,yusgabwlvb,1563551566.9326966,4,2019-07-22-09-04-54
9,0,"0,7461456226596285",53277654580,ecdroalxjh,psaopyiwsu,861741317,2,ehjfwunwxn,1563551566.9326966,9,2019-07-22-09-04-54
10,3,"0,19512019892227683",66010751775,ylnajafonx,mhwrahnehb,745283041,0,jhnusvhmsh,1563551566.9326966,16,2019-07-22-09-04-54
11,19,"0,8950395090491776",45546662582,urknwzolpt,ddsenmeptw,008428241,4,qldrjqgdiz,1563551566.9326966,6,2019-07-22-09-04-54
12,13,"0,9637519061762126",12563485211,ixzfzcwywr,petghpwvof,358783673,17,wmtdokbzyg,1563551566.9326966,7,2019-07-22-09-04-54
13,6,"0,9034054349673653",58328522035,rjxqxkrzcm,vfotskpudh,646064825,7,adwutkucrp,1563551566.9326966,10,2019-07-22-09-04-54
14,12,"0,6604900829914974",16401581386,wgphkbrgwq,pelwqhoebz,646100585,12,wulnahbfiq,1563551566.9326966,0,2019-07-22-09-04-54
15,4,"0,1341989018272597",43638668847,vmmsbdrfjm,beamrudcth,060444042,19,dkwwbsbjkl,1563551566.9326966,14,2019-07-22-09-04-54
16,1,"0,03862737153098439",71647511272,ycuwucbzgp,bswobivool,021338683,18,voqejluriu,1563551566.9326966,14,2019-07-22-09-04-54
17,8,"0,8519048289064296",27424413773,sgmxozsopz,disuahpxcx,254616675,17,yktnjnfhvh,1563551566.9326966,4,2019-07-22-09-04-54
18,5,"0,29459793082768704",12313186266,mhudrtjkog,lnfuuvbuts,046064645,10,rwqeohlfxk,1563551566.9326966,12,2019-07-22-09-04-54
19,9,"0,15588239527338066",65254172167,tfkmcsauxe,abeqwrtyft,800053706,16,lpezwljgul,1563551566.9326966,10,2019-07-22-09-04-54

In [1]:
import pandas as pd
import pyarrow
pd.read_parquet('../GIT/rdr010/data_lake/tests/temp/temp_table.parquet')

   _AGE            _BUDGET         _CPF  _ID _NAME     _PHONE
0    65   6244918494091753  53181010284   54        010351421
1    69   9992794504632634  65758351433   71        467640628
2    89   5386567341780505  35612824227   22        870471876
3    42  17881649868585203  04457563667   39        735457580
4    94  19770442100119134  35351201002   92        750225867
5    47  39287774519326557  50157015881    8        516412730
6    40  59781645175615905  22426562318   53        088778774
7    53     70086789456635  17515374453   67        730166578
8    42    531707916268847  28063713638   63        328014722
9    98   8961445194862371  35813036714   27        063082724